name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install npm 7
        run: npm install --global npm@7
      - name: Install dependencies
        run: npm ci
      - name: Check code style
        run: npm run lint
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install npm 7
        run: npm install --global npm@7
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run tests-only
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install npm 7
        run: npm install --global npm@7
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
