name: Deploy Client

on:
  push:
    branches: [default]
    paths:
      - 'vercel.json'
      - '.github/workflows/deploy-client.yml'
      - 'client/**'
      - 'react-server-list/**'

jobs:
  vercel:
    name: Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Install dependencies
        run: npm install
      - name: Export static client build
        run: npm run --prefix client export
      - name: Deploy
        uses: amondnet/vercel-action@v20.0.0
        with:
          working-directory: ./client/out
          vercel-token: ${{secrets.VERCEL_TOKEN}}
          vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}
          vercel-args: '--prod'
